### ISSUE TITLE
Modulerize Communication System

### ISSUE THREAD

**Issue by ron-popov** [Rogozin-high-school/sat_monitoring_system#12]
The current communication system (HTTP server) looks pretty messy and wouldn't that easy to change it if we need to.  
Maybe we could build a class and pass it each of the possible requests handlers (read magnetometer, write magnetorquer ...).

**Comment by yotam180** [comment]
That's a job for Shai and Or. First (before we modularize anything) **they** have to create a *theoretical* communication protocol and agree to use it. Assigning them for notice.

**Comment by yotam180** [comment]
This is not theirs anymore, and this does not belong here anymore. I am in charge of creating the multipurpose communication protocol. Claiming this as mine :flags:
