### ISSUE TITLE
Move to Vector3D

### ISSUE THREAD

**Issue by ron-popov** [Rogozin-high-school/sat_monitoring_system#28]
Now that @shaiTheKimhi wrote a Vector3D class, maybe we should use it for sensor interactions ?  
Currently we use 3 float variables that represent x, y and z, or a tuple of size 3.  
Passing them a Vector3D object instead would be a lot easier ?  

What do you think @shaiTheKimhi @yotam180  ?

**Comment by yotam180** [comment]
Just a question. Why do you use your own defined vector class and not something like numpy?

Have you considered doing vectors in an ndarray form?

```
import numpy as np

def vector(x = 0, y = 0, z = 0):
    return np.array(x, y, z)
```

That way you can replace `distance_to` with `np.linalg.norm` and many more functionalities (cross product, dot product, etc)

I think it might help you **a lot** in the future when you will have to implement the algorithms to orientate the satellite. Especially when concerning the speed limits of Python.

Opinion, @Rogozin-high-school/core-developers?

**Comment by ron-popov** [comment]
Sure, sounds great 😄
