### ISSUE TITLE
Organize Communications related code

### ISSUE THREAD

**Issue by ron-popov** [Rogozin-high-school/sat_monitoring_system#29]
The communications related code is very messy and needed to be cleaned up. I suggest moving all of it to ```Modules/Communications``` and creating a wrapper class for the HTTP server that would handle HTTP requests and call requests handlers accordingly which would be stored in a different file.  

That way all of the code that is related to handling HTTP request and the communications itself would be stored in one file and all of the code related to handling these request in a different file, if we would want to change the communications protocol we would know exactly where and what we need to change.

**Comment by shaiTheKimhi** [comment]
Why is the communication module automatically creates a connection and sends a message?

**Comment by yotam180** [comment]
For no reason. I told you I have to commit my fixed version. I'll do that tomorrow morning. Hopefully.
