### ISSUE TITLE
Use premade vector library

### ISSUE THREAD

**Issue by ron-popov** [Rogozin-high-school/sat_monitoring_system#31]
As @yotam180 mentioned in issue #28 , it might be a good idea to write Vector3D and Vector2D as wrapper classes for ```numpy.ndarray```. We wouldn't need to implement any vector math operations and it would probably benefit our performence.  

This is only a suggestion since this is your part. So what do you think @shaiTheKimhi  ?

**Comment by ron-popov** [comment]
@shaiTheKimhi ?

**Comment by yotam180** [comment]
U really think ur gonna get answered... U so cute :blush:

**Comment by shaiTheKimhi** [comment]
@ron-popov , we might use it, but it doesn't necessary requires us to remove Vectors for now.

**Comment by shaiTheKimhi** [comment]
I will try it out and see if it is OK

**Comment by ron-popov** [comment]
I am closing this because we started using numpy
