### ISSUE TITLE
Implement different communications system

### ISSUE THREAD

**Issue by ron-popov** [Rogozin-high-school/sat_monitoring_system#4]
Implement a different communications system that will be more similar to the one used in satellites.

**Comment by yotam180** [comment]
We'll make our job ourselves, thank you.

**Comment by ron-popov** [comment]
But you will use part of our current code and I need to rewrite some of it in that case.

**Comment by yotam180** [comment]
Well, not really...
Just open another issue to modularize your code xx
Don't interfere with our issue

**Comment by ron-popov** [comment]
ok

**Comment by yotam180** [comment]
Maybe later.
