### ISSUE TITLE
Document functions, classes, modules, etc.

### ISSUE THREAD

**Issue by yotam180** [Rogozin-high-school/sat_monitoring_system#42]
Our repository seems messy. Very messy. And of course, needs to be well-documented before we leave it to the lower grades.

 - [x] _Modules/Accelerometer/accelerometer.py_ – documentation of `__get_x__(self)` should be in `"""` rather than after `#`. Also it should state that the function returns a `str` and not a `float`, because that's not intuitive. Add the same documentation to every function you have in that file. And make it **below** the function's signature.
 -  [x] _Modules/Accelerometer/accelerometerMT.py_ – should be stated the return type of the axes functions.
 - [x] _Modules/Communications/command_handler.py_ – documentation for the `command_handler` class (what is it?)
 - [x] _Modules/Communications/command_handler.py_ – document all methods of the `command_handler` class, stating their parameters, purpose and return values.
 - [x] _Modules/Communications/command_handler.py_ – Is the `TODO:` comment already done? If so, remove it. Otherwise address an issue to it.
 - [x] _Modules/Communications/communications.py_ – class documentation
 - [x] _Modules/Communications/communications.py_ – Method documentation like required above
 - [x] _Modules/Communications/communications.py_ – Do you really not want to use the Python built-in HTTP modules? (just a question, not a request)
 - [x] _Modules/Communications/communications.py_ – It is good practice to move the constants `__radius` and `__circle_time` to a separate config file, of course keeping the names consistent between your files.
 - [x] _Modules/Communications/communications.py_ – inconsistent operators spacing. For example: `...(field[1] * torque[0] - filed[0]*torque[1]) / (fi...`. Now I'm not saying "make them all spaced or make them all crowded". I'm saying one thing: "MAKE THEM ALL SPACED". Thanks :slightly_smiling_face: 
 - [x] _Modules/Communications/communications.py_ – class documentation for the `controller` class
 - [x] _Modules/Communications/communications.py_ – method documentation (including parameters, purpose and return value[s]) for the functions of the `controller` class.
 - [x] _Modules/Communications/communications.py_ –  inconsistent naming conventions. For example, `TwoDimensionsVerticalVector` - should be `two_dimensions_vertical_vector`. Please fix it across the file.
 - [x] _Modules/Communications/communications.py_ – again operator spacing `get_angle_vector(angle:int)->numpy.ndarray:`. Just fix it throughout the whole file, yeah?
 - [x] _Modules/Gryo/gyro.py_ – documentation of `__get_x__(self)` should be in `"""` rather than after `#`. Also it should state that the function returns a `str` and not a `float`, because that's not intuitive. Add the same documentation to every function you have in that file. And make it **below** the function's signature.
 - [x] _Modules/Gryo/gyroMT.py_ – should be stated the return type of the axes functions.
 - [x] _Modules/Logging/log.py_ – function documentation **below** the function signature, please.
 - [x] _Modules/Logging/log.py_ – do you not have a better method for `# Making sure the log file exists`, maybe using `os` builtins? Not really important but there must be a cuter way.
 - [ ] _Modules/Logging/log_thread.py_ – I don't know if I missed this issue in the previous files I checked above, :point_up_2: but function doc `"""Safely stopping the thread"""` should be written in present simple tense (i.e. `"""Safely stop the thread"""` [as in _"what the function does is to safely stop the thread"_] or `"""Safely stops the thread"""` [as in _"The function safely stops the thread"_]). Please see if I misaddressed it previously.
 - [x] _Modules/Logging/logger.py_ – That's easy. Function documentation.
 - [x] _Modules/Magnetometer/magnetometer.py_ – documentation of `__get_x__(self)` should be in `"""` rather than after `#`. Also it should state that the function returns a `str` and not a `float`, because that's not intuitive. Add the same documentation to every function you have in that file. And make it **below** the function's signature.
 - [x] _Modules/Magnetometer/magnetometerMT.py_ – should be stated the return type of the axes functions.
 - [x] _Modules/Magnetorquer/hBridge.py_ – Class documentation for `hBridge`. Also I think (but I'm not sure about this one) that the preferred name for the class should be `HBridge`. Correct me on that one if I'm wrong.
 - [x] _Modules/Magnetorquer/hBridge.py_ – function documentation for the `hBridge` class should be wrapped in `"""` rather than after `#`.
 - [x] _Modules/Magnetorquer/magnetorquer.py_ – class documentation. What is this class? (one sentence, not more, of course).
 - [x] _Modules/Magnetorquer/magnetorquer.py_ – function documentation. Everywhere. State the type of parameters you expect, what the functions do and what they return (if they do). 
 - [x] _Modules/Magnetorquer/magnetorquerMT.py_ – Same comments like in _magnetorquer.py_ - function documentation and class documentation.
 - [x] _Modules/Vector/Vector2D.py_ – class documentation. What does this class do? 
 - [x] _Modules/Vector/Vector2D.py_ – spacing between functions should be 1 empty line, not more and not less. Please make sure this is the situation.
 - [x] _Modules/Vector/Vector2D.py_ – function documentation.
 - [x] _Modules/Vector/Vector3D.py_ – class documentation. What does this class do? 
 - [x] _Modules/Vector/Vector3D.py_ – spacing between functions should be 1 empty line, not more and not less. Please make sure this is the situation.
 - [x] _Modules/Vector/Vector3D.py_ – function documentation.
 - [x] _Communication/satprot.py_ – class documentation for `InMsg` and `OutMsg`.
 - [x] _Communication/satprot.py_ – class documentation for `Connection`.
 - [x] _Communication/satprot.py_ – function documentation for everything, what the functions do, what they accept as parameters and what they return. 
 - [x] _Communication/satprot.py_ – remove the test code at the bottom. A module file should only provide an interface, not execute test commands.

Please address these points, @shaiTheKimhi and @ron-popov  (whichever points belong to you, of course). First priority, of course, is making a simulation system for Sunday. Second priority after that is cleaning the repository.

I'm going to make the same code-smell examination in other repositories too in the next few days. If you're good friends please "warn" @nofearOnline . :wink: 

More than invited to read my book on the subject, [Writing Non-Shitty Code](https://orly-appstore.herokuapp.com/generate?title=Writting%20Non-Shitty%20Code&top_text=Advice%20and%20guidelines%20for%20writing%20understandable%20code.&author=Yotam%20Salmon&image_code=7&theme=4&guide_text=The%20Definitive%20Guide&guide_text_placement=bottom_right).

Sincerely,
Yotam.

**Comment by ron-popov** [comment]
😨

**Comment by nofearOnline** [comment]
😨

**Comment by yotam180** [comment]
> _"A journey of a thousand miles begins with a single step"_ 
> the Chinese philosopher Laozi

Check-mark by check-mark we will together solve this issue. No worries.

**Comment by yotam180** [comment]
I am still waiting for this issue to be addressed. @Rogozin-high-school/satellite-contributors

**Comment by shaiTheKimhi** [comment]
> "The two most important days in your repo are the day you open it and the day you figure out why"
Mark Twain

**Comment by shaiTheKimhi** [comment]
> "If you don't read the documentations you are uniformed,
if you read the documentations you are misinformed"

**Comment by yotam180** [comment]
I like the second one, although its author was just mislead by bad documentation. I just ask for good docs.

**Comment by shaiTheKimhi** [comment]
Documentation can never be really objective

**Comment by yotam180** [comment]
Objective? It's documentation, it shouldn't claim anything. It just instructs people about your code...
Are you sure you know what documentation is?

Anyway, the fact is that I will reject all code which is poorly documented. So you better document your shit.

**Comment by ron-popov** [comment]
@shaiTheKimhi Can you document you modules (Control and Field) ?

**Comment by yotam180** [comment]
Hahahahaha

**Comment by ron-popov** [comment]
@shaiTheKimhi ?

**Comment by yotam180** [comment]
The poor guy is still hopeful to get an answer. Pathetic.

**Comment by nofearOnline** [comment]
lol

**Comment by shaiTheKimhi** [comment]
can you extend.
p.s @yotam180 , you were not asked so do not intervene please

**Comment by shaiTheKimhi** [comment]
I mean give a specification what should be specified as it is partially documented

**Comment by shaiTheKimhi** [comment]
@yotam180 , you better keep informative language and keep your shit together.

**Comment by yotam180** [comment]
Shai, let me put, hands down, a few points;
1. Elaboration can be found in the first post.
2. P.s. you were not asked to contribute to our lab repository. I do really appreciate your willingness to help us, but at the time, we do prefer to keep our code original and well-suited to our precisely defined protocol. If you wish to help us with the laboratorio system, please let's talk and make sure we are likely to be more than glad to accept you into the contribution process.
3. Glad you started watching Rick and Morty. Finally some culture, great job. 
4. My shit is always together, thanks for minding.

**Comment by shaiTheKimhi** [comment]
I think the second remark is not suited for this issue

**Comment by shaiTheKimhi** [comment]
p.s this repo is monitored by adult supervision, so I think the conversation is ought to be more respectful and less cynical

**Comment by yotam180** [comment]
Yeah, if you really want to be strict with the conversation topic, let me correct no.2 to "Hey, this is my issue, I will comment as much as I wish and see appropriate". I think that's a more selfish approach, but it settles the argument.

Apart from my supervision this repository is not _really_ monitored, so don't have to be much bothered about that. Except for that, I believe I might correct you twice here:
1. I'm not being **cynical**, I do believe you have really helpful contributions. I _am_ being **sarcastic**.
2. I believe you're bothered by the vulgarity of the comment rather than the sarcasm (or cynicism).

If it bothers you so much, I have refactored it a bit to be softer. You can consider if SFW now.

**Comment by yotam180** [comment]
36/37 is enough for closing. Thanks, @ron-popov :+1:
