### ISSUE TITLE
Modularize the magnet sensor interface

### ISSUE THREAD

**Issue by yotam180** [Rogozin-high-school/sat_monitoring_system#5]
So it could work with different modules and crap like that.

**Don't mix communication and sensor reading.**

**Comment by ron-popov** [comment]
Do you mean the magnetometer? because there is already a module for it, we just need to implement it.

**Comment by yotam180** [comment]
I mean whatever you need to do to your code to make it more modular to work with an external (i.e. made by Or & I) communication system. I don't really care what kinds of modifications these are.

**Comment by ron-popov** [comment]
Done
