### ISSUE TITLE
Null bytes in config file

### ISSUE THREAD

**Issue by ron-popov** [Rogozin-high-school/sat_monitoring_system#60]
For some reason when i try running ```A0.py``` i get an error saying source files can contain null bytes in ```from . import config``` in ```magnetometer_factory.py``` so i assume this is a problem either with ```config.py``` or that line.

Can you look at that @shaiTheKimhi ?

**Comment by shaiTheKimhi** [comment]
you @ron-popov  created the config, moreover, I do not see any reason for this file to contain null  bytes.

**Comment by yotam180** [comment]
So you are just going to assign each other, and neither one of you is actually going to do it.
Huh.

**Comment by ron-popov** [comment]
Fixed in 1079089b52a84d88c638518886f23f609ff00da7
