### ISSUE TITLE
KeyboardInterrupt in log_thread.py

### ISSUE THREAD

**Issue by bslava** [Rogozin-high-school/sat_monitoring_system#7]
log_thread.py contains platform specific exception KeyboardInterrupt. Would you expect your satellite system supports it as well?

**Comment by ron-popov** [comment]
Not really, I only used it because it works at the moment.  
What other methods could I use to stop the server?

**Comment by yotam180** [comment]
Helper thread that waits for input? Halting command inside the server protocol? 
You want full control over the satellite **remotely**, so I think the second option is better.

**Comment by ron-popov** [comment]
Oh, I haven't thought of that.

**Comment by ron-popov** [comment]
I believe this can be closed now.
