### ISSUE TITLE
thread synchronization in log.py

### ISSUE THREAD

**Issue by bslava** [Rogozin-high-school/sat_monitoring_system#8]
What do you think about moving log_lock from main.py to log.py. In this case any usage of logger will be protected w/o any additional code?

**Comment by ron-popov** [comment]
In that case, could we also move magnetometer_lock to magnetometer.py?

**Comment by bslava** [comment]
It depends. If you are writing this module from scratch and it will be used in the multi-threaded environment only, then I'd do so. Otherwise I'd create a class (like MagnetometerMT) that derived from the magnetometer class and would add the lock to it.

By the way, in Python you do not need a special lock. You could write something like:
```python
with self.lock:
    do something
```

**Comment by ron-popov** [comment]
Could you look at 09a77d999c9914146b164145a768b1b9cb3f3b6d ?  
Is that what you meant?

**Comment by bslava** [comment]
Yes.

Just one more comment. I do not think log class should be aware about existence of config one. I would pass file name though to a constructor. In this case you would be able to reuse this class in other projects where config class does not exist.

**Comment by yotam180** [comment]
His bits of advice are gold ^
I am not a part of this code development, but I can assure that rethinking which classes should know which classes before implementing them usually prevents the creation of spaghetti code. 

Also I would convert the comments into valid _PEP8_ docstrings (`"""Docs"""` below the declaration line and not `#Docs` before it)
