### ISSUE TITLE
file operations in log.py

### ISSUE THREAD

**Issue by bslava** [Rogozin-high-school/sat_monitoring_system#9]
Why do you use "a+" and "r+" while opening a file? I think "a" and "r" will be enough. Moreover, on some Linux systems behavior of "a+" can differ.

**Comment by ron-popov** [comment]
Ok, I will change it.

**Comment by ron-popov** [comment]
Fixed in commit 21f36f7dd7d4bfffd5d427a873737ba4463ffd58.  
Is it ok now?

**Comment by bslava** [comment]
Yes. In addition you could add a nested with open(...). In his case you won't have to deal with flush() and close()...
